version: 2
updates:
  - directory: /
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    groups:
      major:
        update-types:
          - major
      minor:
        update-types:
          - minor
          - patch
    allow:
      - dependency-type: "all"

  - directory: /
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  # Dependabot doesn't support docker-compose yet
  # - directory: /
  #   package-ecosystem: "docker"
  #   schedule:
  #     interval: "weekly"
