version: '3'

services:
  webpack:
    container_name: dim-webpack
    image: node:18
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: >
      bash -c "git config --global --add safe.directory /usr/src/app && yarn install --frozen-lockfile --prefer-offline && yarn start"
    environment:
      - NODE_ENV=development
      - DOCKER=true
    restart: 'no'
    volumes:
      - .:/usr/src/app
      - ./config/:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: {}

networks:
  dim:
    name: dim
